### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by arademaker** [dwf/moin2rst#2]
Code is not handling tables. Any idea about how hard would be to implement it? What about a simple workaround, copy the table code verbatim to the output? Is it possible in the current code? Can someone give directions on how to implement it? The formatter code is not clear, I am still trying to understand how the code works.

**Comment by dwf** [comment]
I haven't touched this code in over a decade I'm afraid I don't have the time nor the interest in developing it further. I'll be updating the README and archiving the repository.
